log4r_config:
    pre_config:
        global:
            level: ALL
    
    # define all outputters (incl. formatters)
    outputters:
    - type: RollingFileOutputter
      name: log_file
      filename: "log/sample-.log"
      maxsize: "5242880" #5MB
      max_backups: "5"
      formatter:
          date_pattern: '%Y-%m-%d %H:%M:%S'
          pattern     : '[%d %C %l]: %m'
          type        : PatternFormatter
    - type: StdoutOutputter
      name: console
      formatter:
          pattern     : '%m'
          type        : PatternFormatter
    loggers:
    - name      : event-store
      trace     : 'true'
      level: INFO #Change to DEBUG to see what's going on in the event store.
      outputters:
      - log_file
    - name      : common-domain::sample
      trace     : 'true'
      outputters:
      - log_file
      - console
      
